# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [3]:
import numpy as np
print(np.__version__)

1.18.5


#### 3. Create a null vector of size 10

In [4]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [5]:
arr = np.zeros(10)
print(arr.size * arr.itemsize)

80


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [31]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [7]:
arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49

In [8]:
arr = np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last)

In [9]:
arr[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
arr = np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [11]:
arr = np.array([1,2,0,0,4,0])

print(np.where(arr != 0))

(array([0, 1, 4], dtype=int32),)


#### 11. Create a 3x3 identity matrix

In [12]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [13]:
arr = np.random.random((3,3,3))
arr

array([[[0.47776121, 0.5657957 , 0.0571776 ],
        [0.73398773, 0.25488096, 0.26630085],
        [0.27634068, 0.07291801, 0.6256337 ]],

       [[0.11225567, 0.49736734, 0.95544026],
        [0.93937012, 0.89644257, 0.44050008],
        [0.6932553 , 0.89093127, 0.46275885]],

       [[0.6017149 , 0.37431948, 0.87922324],
        [0.51227702, 0.53015416, 0.21746275],
        [0.80829133, 0.29080358, 0.63409911]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [14]:
arr= np.random.random((10,10))
np.sort(arr)
print(arr[0,0])
print(arr[9,9])

0.5823486782495049
0.03306323858510729


#### 14. Create a random vector of size 30 and find the mean value

In [15]:
arr = np.random.random(30)
arr

array([0.52431502, 0.54210289, 0.32697854, 0.08918739, 0.94726419,
       0.00476238, 0.61528042, 0.63705676, 0.60334367, 0.67490069,
       0.73942283, 0.87738828, 0.48607733, 0.51341396, 0.61083048,
       0.00173068, 0.83011599, 0.17155819, 0.63160416, 0.64822729,
       0.63606599, 0.11323856, 0.19089988, 0.88507203, 0.5790308 ,
       0.13759119, 0.52354483, 0.24675558, 0.17957405, 0.95520664])

#### 15. Create a 2d array with 1 on the border and 0 inside

In [17]:
n = int(input())
arr = np.ones((n,n))
for i in range(1,n-1):
    for j in range(1,n-1):
        arr[i,j] = 0
arr

5


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array?

In [21]:
arr = np.ones((5,5))
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
arr

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan
False
False
nan
True
False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [24]:
arr = np.diag(1+np.arange(4), k=-1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [27]:
arr = np.zeros ((8,8), dtype=int)
arr[1::2, ::2]= 1
arr[::2, 1::2] = 1
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [38]:
import numpy as np

arr=np.empty((6,7,8))

c=0
for idx,x in np.ndenumerate(arr):
    
    if(c==100):
        print(idx)
    c+=1

(1, 5, 4)
